In [1]:
# Importing Libraries 
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import io
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report

# Uploading data
from google.colab import files
uploaded = files.upload()

Saving img_df.csv to img_df.csv


In [35]:
# Putting data into a pandas DataFrame
img_df = pd.read_csv(io.BytesIO(uploaded['img_df.csv']))
X = img_df.iloc[:, :-1]
y = pd.get_dummies(img_df.iloc[:, -1:])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25)

# Creating & Initiating Model
model = keras.Sequential([keras.layers.Dense(1600, input_shape=(40449,), activation='relu'),
                          keras.layers.Dense(1600, activation="relu"),
                          keras.layers.Dense(6, activation="softmax")
])

model.compile(optimizer='Adadelta', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

# Setting up verbose=1 - prints out some results after each epoch
model.fit(X_train, y_train, batch_size=6, epochs=100, verbose=1)

# Model Evalution
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)

model.summary()

print("Test Loss: ", test_loss)
print("Test Accuracy: ", test_acc)

Epoch 1/100
70/70 [==============================] - 23s 323ms/step - loss: 1.9136 - categorical_accuracy: 0.1562
Epoch 2/100
70/70 [==============================] - 23s 323ms/step - loss: 1.7877 - categorical_accuracy: 0.2236
Epoch 3/100
70/70 [==============================] - 23s 323ms/step - loss: 1.7437 - categorical_accuracy: 0.2716
Epoch 4/100
70/70 [==============================] - 23s 325ms/step - loss: 1.6974 - categorical_accuracy: 0.2668
Epoch 5/100
70/70 [==============================] - 23s 324ms/step - loss: 1.6606 - categorical_accuracy: 0.3341
Epoch 6/100
70/70 [==============================] - 23s 324ms/step - loss: 1.6496 - categorical_accuracy: 0.3293
Epoch 7/100
70/70 [==============================] - 23s 324ms/step - loss: 1.6007 - categorical_accuracy: 0.3918
Epoch 8/100
70/70 [==============================] - 23s 324ms/step - loss: 1.5774 - categorical_accuracy: 0.4014
Epoch 9/100
70/70 [==============================] - 23s 323ms/step - loss: 1.5877 - cat

In [42]:
# More Model Evaluation
y_pred = model.predict(X_test)
print(confusion_matrix(y_test.values.argmax(axis=1), y_pred.argmax(axis=1)))

[[ 3  2  2  1  2  8]
 [ 3  2  2  2  1  5]
 [ 0  0 12  2  1 16]
 [ 1  1  0  3  2 15]
 [ 1  1  3  2  3 15]
 [ 1  2  2  4  2 17]]


In [41]:
print(classification_report(y_test.values.argmax(axis=1), y_pred.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.33      0.17      0.22        18
           1       0.25      0.13      0.17        15
           2       0.57      0.39      0.46        31
           3       0.21      0.14      0.17        22
           4       0.27      0.12      0.17        25
           5       0.22      0.61      0.33        28

    accuracy                           0.29       139
   macro avg       0.31      0.26      0.25       139
weighted avg       0.33      0.29      0.27       139

